# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js runtime as a parent image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy the remaining source files and build the project
COPY src ./src
COPY tsconfig.json ./
RUN npm run build

# Use a smaller runtime image for the final build
FROM node:18-alpine AS release

# Set the working directory
WORKDIR /app

# Copy the built application and node modules
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules

# Set environment variables (ensure you replace with actual values)
ENV OPENROUTER_API_KEY=your-api-key-here
ENV OPENROUTER_DEFAULT_MODEL=optional-default-model

# Specify the command to run the server
ENTRYPOINT ["node", "build/index.js"]